[manager]
cwd = { fg = "#76946A" }

# Hovered
hovered         = { fg = "#303446", bg = "#8caaee" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#e5c890", italic = true }
find_position = { fg = "#6A9589", bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "#a6d189", bg = "#a6d189" }
marker_cut      = { fg = "#e78284", bg = "#e78284" }
marker_selected = { fg = "#8caaee", bg = "#8caaee" }

# Tab
tab_active   = { fg = "#303446", bg = "#c6d0f5" }
tab_inactive = { fg = "#c6d0f5", bg = "#51576d" }
tab_width    = 1

# Count
count_copied   = { fg = "#303446", bg = "#a6d189" }
count_cut      = { fg = "#303446", bg = "#e78284" }
count_selected = { fg = "#303446", bg = "#8caaee" }

# Border
border_symbol = "│"
border_style  = { fg = "#838ba7" }

# Highlighting
syntect_theme = "~/.config/yazi/Catppuccin-frappe.tmTheme"

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#51576d", bg = "#51576d" }

# Mode
mode_normal = { fg = "#303446", bg = "#8caaee", bold = true }
mode_select = { fg = "#303446", bg = "#a6d189", bold = true }
mode_unset  = { fg = "#303446", bg = "#eebebe", bold = true }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8caaee", bg = "#51576d" }
progress_error  = { fg = "#e78284", bg = "#51576d" }

# Permissions
permissions_t = { fg = "#8caaee" }
permissions_r = { fg = "#e5c890" }
permissions_w = { fg = "#e78284" }
permissions_x = { fg = "#a6d189" }
permissions_s = { fg = "#838ba7" }

[input]
border   = { fg = "#8caaee" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#8caaee" }
active   = { fg = "#6A9589" }
inactive = {}

[tasks]
border  = { fg = "#8caaee" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#414559" }
cand            = { fg = "#76946A" }
rest            = { fg = "#949cbb" }
desc            = { fg = "#6A9589" }
separator       = "  "
separator_style = { fg = "#626880" }

[help]
on      = { fg = "#6A9589" }
exec    = { fg = "#76946A" }
desc    = { fg = "#949cbb" }
hovered = { bg = "#626880", bold = true }
footer  = { fg = "#51576d", bg = "#c6d0f5" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#76946A" },

	# Videos
	{ mime = "video/*", fg = "#e5c890" },
	{ mime = "audio/*", fg = "#e5c890" },

	# Archives
	{ mime = "application/zip",             fg = "#6A9589" },
	{ mime = "application/gzip",            fg = "#6A9589" },
	{ mime = "application/x-tar",           fg = "#6A9589" },
	{ mime = "application/x-bzip",          fg = "#6A9589" },
	{ mime = "application/x-bzip2",         fg = "#6A9589" },
	{ mime = "application/x-7z-compressed", fg = "#6A9589" },
	{ mime = "application/x-rar",           fg = "#6A9589" },

	# Fallback
	{ name = "*", fg = "#c6d0f5" },
	{ name = "*/", fg = "#8caaee" }
]
