#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a VSCodium desktop='^3' follow=on
bspc rule -a feh desktop='^5' follow=on
bspc rule -a vlc desktop='^6' state=fullscreen
bspc rule -a mpv desktop='^6' state=fullscreen
bspc rule -a Brave-browser desktop='^7' follow=on
bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a libreoffice-startcenter desktop='^8'
bspc rule -a zoom desktop='^9' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

# Border
bspc config focused_border_color        "#476279"
bspc config normal_border_color         "#322b3a"
bspc config active_border_color         "#322b3a"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &
# Low battery notifier
# notify-send "Test"
sh ~/.config/bspwm/scripts/low_bat_notifier.sh &
